autolabeler:
  - label: 'Type: documentation'
    files:
      - '*.md'
    # Checks there is no word character (alphanumeric & underscore) before target words, or after to avoid accidental matches
    title:
      - '/(?<![\w])((doc)|(docs)|(documentation))(?![\w])/i'
  - label: 'Type: fix'
    branch:
      - '/fix\/.+/'
    title:
      - '/(?<![\w])((fix)|(fixes))(?![\w])/i'
  - label: 'Type: feature'
    branch:
      - '/feature\/.+/'
    title:
      - '/(?<![\w])((feat)|(feature))(?![\w])/i'
  - label: 'Type: enhancement'
    branch:
      - '/enhancement\/.+/'
    title:
      - '/(?<![\w])((enhancement)|(enhancements))(?![\w])/i'
  - label: 'Type: buildscripts'
    files:
      - '*.yml'
    branch:
      - '/buildscripts\/.+/'
    title:
      - '/(?<![\w])((buildscript)|(buildscripts))(?![\w])/i'
